language: rust
dist: trusty
sudo: required
cache: cargo

services:
- rabbitmq

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

os:
- linux
- osx

rust:
- stable
- beta
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - rust: stable
    env: RUSTFMT=YES 
    script:
    - rustup component add rustfmt-preview
    - cargo fmt -- --write-mode=diff

before_install:
- |
  if [ "$TRAVIS_OS_NAME" = osx ]
  then
    brew update
    brew install rabbitmq
    brew services run rabbitmq
  fi

script:
- cargo build --all
- cargo test --all

before_deploy:
- export MDBOOK_VERSION=0.1.5
- "wget -O mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz"
- tar xf mdbook.tar.gz
- ./mdbook build ./guide

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: gh-pages
  local_dir: guide/book
  on:
    branch: master
    repo: kureuil/batch-rs
    rust: stable
    condition: $RUSTFMT != YES -a $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
