language: rust
sudo: required
dist: trusty
cache: cargo

services:
  - rabbitmq

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - rust: stable
    env: RUSTFMT=YES 
    script:
    - rustup component add rustfmt-preview
    - cargo fmt -- --write-mode=diff
  - rust: stable
  - rust: beta
  - rust: nightly

script:
  - cargo test --all

before_deploy:
  - wget -O mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.3/mdbook-v0.1.3-x86_64-unknown-linux-gnu.tar.gz
  - tar xf mdbook.tar.gz
  - ./mdbook build ./guide

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: gh-pages
  local_dir: guide/book
  on:
    branch: master
    repo: kureuil/batch-rs
    rust: stable
    condition: $RUSTFMT != YES

notifications:
  email:
    on_success: never
